// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4701b025-e21d-4d04-b3cc-5d819d761fdb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_b6ShPGPkO",
    "aws_user_pools_web_client_id": "72rk76f7bf04ktilei5qtfhu2u",
    "oauth": {},
    "aws_user_files_s3_bucket": "securacity-user-content-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "API": {
        "aws_appsync_graphqlEndpoint": "https://ib45x6f4pnhoddcpek2gpyunyi.appsync-api.us-east-1.amazonaws.com/graphql",
        "aws_appsync_region": "us-east-1",
        "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
    }
};


export default awsmobile;
